#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PwrBurgers.Resource", IsApplication=true)]

namespace PwrBurgers
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int FavoritesIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int green_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int MeatLoversIcon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pwrIcon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int PwrLogo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int VeggieLoversIcon = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070013
			public const int AddUserButton = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int CatsView = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int MyButton = 2131165205;
			
			// aapt resource value: 0x7f07001d
			public const int aboutButton = 2131165213;
			
			// aapt resource value: 0x7f070009
			public const int amountEditText = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int burgerImageView = 2131165187;
			
			// aapt resource value: 0x7f070018
			public const int burgerListView = 2131165208;
			
			// aapt resource value: 0x7f070004
			public const int burgerNameTextView = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int callTextView = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int cancelButton = 2131165192;
			
			// aapt resource value: 0x7f07001a
			public const int cartButton = 2131165210;
			
			// aapt resource value: 0x7f07000c
			public const int cartView = 2131165196;
			
			// aapt resource value: 0x7f07001e
			public const int dataBaseButton = 2131165214;
			
			// aapt resource value: 0x7f070011
			public const int dbUserName = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int descriptionTextView = 2131165190;
			
			// aapt resource value: 0x7f070020
			public const int externalMapButton = 2131165216;
			
			// aapt resource value: 0x7f07000b
			public const int fragmentContainer = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout1 = 2131165199;
			
			// aapt resource value: 0x7f070016
			public const int linearLayout2 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout3 = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int logoImageView = 2131165209;
			
			// aapt resource value: 0x7f070002
			public const int mainScrollView = 2131165186;
			
			// aapt resource value: 0x7f07001c
			public const int mapButton = 2131165212;
			
			// aapt resource value: 0x7f070012
			public const int meowsCount = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int orderButton = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int orderSummaryText = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int phoneNumberTextView = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int priceTextView = 2131165191;
			
			// aapt resource value: 0x7f07000e
			public const int proceedOrderButton = 2131165198;
			
			// aapt resource value: 0x7f070022
			public const int rayPictureImageView = 2131165218;
			
			// aapt resource value: 0x7f07001f
			public const int rotationsButton = 2131165215;
			
			// aapt resource value: 0x7f070005
			public const int shortDescriptionTextView = 2131165189;
			
			// aapt resource value: 0x7f07001b
			public const int takePictureButton = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int textView1 = 2131165217;
			
			// aapt resource value: 0x7f070010
			public const int textView2 = 2131165200;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BurgerDetailView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BurgerMenuView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int BurgerRowView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CartView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DataBaseView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FavoriteBurgerFragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MainMenu = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MeatLoversFragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PwrBurgerMapView = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int rotationsView = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int TakePictureView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int VeggieLoversFragment = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int crazyFrog = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int button_text = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
